### ISSUE TITLE
Добавь возможность заказывать пиво 

### ISSUE THREAD

**Issue by vvl1m** [TheFunnyDay/TheFunnyDay.github.io#3]
Хочется пива

**Comment by TheFunnyDay** [comment]
> Хочется пива 

- [ ] Тоже хочу. Пошли пить в кб

**Comment by vvl1m** [comment]
> > Хочется пива 
> 
> - [ ] Тоже хочу. Пошли пить в кб
    @ImgBotApp

**Comment by vvl1m** [comment]
# Юае бан бан бпн бан бан # - [ ] - - - _@![1616816204844.jpg](https://user-images.githubusercontent.com/54174788/114001218-2ab48000-9875-11eb-935e-495e1390e463.jpg)   
- # - - [ ]  ~~![Uploading - [ ] # - [ ] - [ ] - [ ] - ##### - [x] [ ] 1616525221737.jpg …]# # ### ()@ImgBotApp ![1616525221737.jpg](https://user-images.githubusercontent.com/54174788/114001278-36a04200-9875-11eb-887f-6d9d33c96bf3.jpg)![1616525184719.jpg](https://user-images.githubusercontent.com/54174788/114001279-36a04200-9875-11eb-9c47-7fcb63a20c5c.jpg)![1616525184719.jpg](https://user-images.githubusercontent.com/54174788/114001277-36a04200-9875-11eb-859d-53d20123e79d.jpg)____**пизлец****_~~```
Россия в коде 
```~~_******____~~_
